### PR TITLE
fix: Fixed indexing issue and inv() calls in are.m

### PR DESCRIPTION
**Pull request by jasonnicholson**
fix: Fixed indexing issue. #4 
perf: replaced inv with proper backslash use.

### CODE REVIEW

**Comment by DanielMartensson** [comment]
I understand. Good point.

**Comment by DanielMartensson** [comment]
One more question. 
Can you try some simulations


```
sys = ss(0, [0 1; -2 -3], [0; 1]);
K = lqe(sys, [1 0; 0 1], 1)
K =

   0.6558  -0.2530
  -0.2530   0.3088
>> K = lqe(sys, [5.1 0; 0 2.5], 0.1)
K =

   6.9733  -0.8362
  -0.8362   3.0534

>> K = lqe(sys, [25.15 0; 0 1.92], 10.24)
K =

   1.1559  -0.4558
  -0.4558   0.2869

>> sysd = c2d(sys, 0.01); % Discrete system
>> K = lqe(sysd, [1 0; 0 1], 1)
K =

   0.7214  -0.2742
  -0.2819   0.7029
>> K = lqe(sysd, [5.1 0; 0 5.1], 10)
K =

   0.6683  -0.3346
  -0.3319   0.6460

>> K = lqe(sysd, [5.1 0; 0 2.5], 0.9)
K =

   9.9990e-01   9.8512e-03
  -1.9702e-02   9.7035e-01

>> K = lqe(sysd, [5.1 0; 0 2.5], 9)
K =

   0.7299  -0.4404
  -0.2739   0.5465

>> K = lqe(sysd, [25.15 0; 0 1.92], 10.24)
K =

   0.9026  -0.5982
  -0.1113   0.3979

>>
```

Check with MATLAB as well. 


Do you get the same?

**Comment by jasonnicholson** [comment]
This is what I found:

image

**Comment by DanielMartensson** [comment]
Ok! That's good.

Can you try to see if you can get an observer to work with this example?

```
G = tf(1, [1 1.5 1]);
[u, t] = gensig('square', 10, 10, 100);
y = lsim(G, u, t);
yn = y + randn(1, length(y)); % Random noise.
sys = tf2ss(G);
Q = [0.1 0; 0 0.1];
R = 1.5;
K = lqe(sys, Q, R);
delay = sys.delay;
A = sys.A;
B = sys.B;
C = sys.C;
D = sys.D;
```

The goal here is to create an observer. This is only an ideal pratice. 

```
observer = ss(delay, A - K*C, [B K], C, [D 0]);
yobs = lsim(observer, [u; yn], t);
close
plot(t, yn, t, yobs)
```

image

**Comment by DanielMartensson** [comment]
I made a TODO at the `ReadMe.md`

**Comment by jasonnicholson** [comment]
> Can you try to see if you can get an observer to work with this example?

Do you mean OKID?

If you mean OKID, I think the equations to use are either:

- Zero initial conditions of the observer.
image
- Or this one if the initial conditions are zero.
image

What's odd with the example you are using is that the y is 0 initially without noise. When you add noise, y(0) is most likely not zero. I am trying to think through the consequences of the fact that you don't have a D matrice in your example, yet noise will make it seem like you do have one because y(0) is not 0. Therefore, it may make sense to remove the D matrice when you know you don't have one. As well, I need to think through the sensitivity of the equations.

Regarding your okid.m file, I have to work through the math and code to ensure that errors are not propagated through the algorithm. This takes deep thought and time.

Once I am confident that okid is formulated well, it still may be noise sensitive. If it is, I am going to use a second derivative regularization. This type of regularization should penalize a non-smooth impulse response. To understand this regularization, read about it in the 3 part series here: https://mathformeremortals.wordpress.com/2013/01/29/introduction-to-regularizing-with-2d-data-part-1-of-3/

I have worked through chapter 6 of Jer-Nan Juang's book several times. There are several algorithms:

- okid. Sections 6.1-6.4
- Observer estimation from output residuals. This one allows for refinement of the observer gains once a model is found. i.e. After okid, run this to refine the observer gains.
- Backward-Time Observer gain. This one helps to check okid and help to decide the order of the identified model.

I have also gathered Jer-Nan Juang's later papers. He has several that refine okid. He has also started applying okid to Linear Time-Varying (LTV) Systems in the last decade. Also, I see the possibility of running okid in real-time with recursive least squares. Maybe, it's possible to extend okid for the Extended Kalman Filter and Unscented Kalman Filter; I honestly don't know. Interesting thought though. For now, I need a foundation in the algorithm before we can extend it.

**Comment by jasonnicholson** [comment]
I think this is what you are looking for.
image

image

**Comment by jasonnicholson** [comment]
We can add unit tests in the future to test for output changes. The examples in this conversation could be used as tests. While it doesn't guarantee the math is correct, it should detect changes to the outputs if something is wrong internally.

**Comment by DanielMartensson** [comment]
> I think this is what you are looking for. image
> 
> image

Yes. It the same for you too. Good.
Try this one.

```
G = tf(1, [1 1.5 1]);
[u, t] = gensig('square', 10, 10, 100);
u = [u*5 u*2 -u 10*u -2*u];
t = linspace(0, 50, length(u));
y = lsim(G, u, t);
close
yn = y + randn(1, length(y)); % Random noise.

% Identify the model
[sysd, K1] = cca(u, yn, 30, t(2), 0, 2); % 0 = delay. t(2) = sample time. 2 = model order

% Create an observer
delay = sysd.delay;
A = sysd.A;
B = sysd.B;
C = sysd.C;
D = sysd.D;
Q = [0.1 0; 0 0.1];
R = 1.5;
K2 = lqe(sysd, Q, R);
observer = ss(delay, A - K2*C, [B K2], C, [D 0]);
observer.sampleTime = sysd.sampleTime;

% Simulate the observer
yobs = lsim(observer, [u; yn], t);
close
plot(t, yn, t, yobs(1:2:end))
```

This is the result should be very bad because of bad tuning of ´K2´ matrix.

image

image

Now try the identified matrix `K1`

```
observer = ss(delay, A - K1*C, [B K1], C, [D 0]);
observer.sampleTime = sysd.sampleTime;
yobs = lsim(observer, [u; yn], t);
close
plot(t, yn, t, yobs(1:2:end))
```

Result

image


image

**Comment by DanielMartensson** [comment]
> We can add unit tests in the future to test for output changes. The examples in this conversation could be used as tests. While it doesn't guarantee the math is correct, it should detect changes to the outputs if something is wrong internally.

Yes. I think we should have some kind of documentation of the status of each `.m` file. Future, TODO etc. Good point.

**Comment by jasonnicholson** [comment]
The latest example stops on cca.
image

image

**Comment by DanielMartensson** [comment]
Now it should work. 
call `updatemataveid`

Try the CCA example in the example folder.

**Comment by jasonnicholson** [comment]
First Figure:
image

Second Figure:
image

**Comment by DanielMartensson** [comment]
Great! It works for you.

I have been working on this repository for a while now, as you can see. 

I have find a way to implement kalman filters for all identification algorithms.

**Comment by DanielMartensson** [comment]
Did you know that if you compute:

```matlab
w = w*1/2;
```

Inside the `cca.m`, you will get this result.

image

**Comment by jasonnicholson** [comment]
> Did you know that if you compute:
> 
> ```matlab
> w = w*1/2;
> ```
> 
> Inside the `cca.m`, you will get this result.
> 
> image

No, I did not know that. I am missing the significance of this. I am unfamiliar with cca. Talk to you soon.

**Pull request merged**
